---
- name: Get show running-config of Cisco device
  hosts: all
  gather_facts: yes
  tasks:
    - name: Backup current switch config (ios)
      cisco.ios.ios_config:
        backup: yes
          - show running-config
      register: backup_ios_location
