- name: Cambia descripcion test
  hosts: all
  gather_facts: yes
  tasks:
    - name: Merge provided OSPF V2 configuration
    cisco.ios.ios_ospfv2:
      config:
        processes:
          - process_id: 22
            max_metric:
              router_lsa: true
              on_startup:
                time: 110
            areas:
              - area_id: "5"
                capability: true
                authentication:
                  enable: true
              - area_id: "10"
                authentication:
                  message_digest: true
                nssa:
                  default_information_originate:
                    metric: 10
                  translate: suppress-fa
                default_cost: 10
                filter_list:
                  - name: test_prefix_in
                    direction: in
                  - name: test_prefix_out
                    direction: out
            network:
              - address: 198.51.100.0
                wildcard_bits: 0.0.0.255
                area: 5
            default_information:
              originate: true
            passive_interfaces:
              default: true
              interface:
                set_interface: false
                name:
                  - GigabitEthernet0/2
                  - GigabitEthernet0/3
