---
- name: Show running-config of inventory
  hosts: all
  tasks:
    - name: Show running-config
      gather_facts: no
      command: show running
      register: running_config

    - debug:
        var: running_config.stdout_lines
