---
- name: Get show running-config of Cisco device
  hosts: all
  gather_facts: no
  tasks:
    - name: Show running-config
      ios_command:
        commands:
          - show running-config
      register: running_config

    - debug:
        var: running_config.stdout_lines
